-- admin/admin calculated by https://bcrypt-generator.com/
INSERT INTO PERSON (USERNAME, PASSWORD_HASH, ROLE) VALUES ('admin', '$2a$12$jYJYfiKpP7QRK9nCg9E9ueoHB0vg546SyvgHAeLpGIESaNXg734JO', 'ADMIN');
INSERT INTO PERSON (USERNAME, PASSWORD_HASH, ROLE) VALUES ('user1', '$2a$12$uLWxRfYra1wryiJGjFNpZukBd0arIYvudSn12pJ6hm9XHNIG5MSi2', 'USER');